apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: game
  name: gameserver
  labels:
    app: gameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
      - name: gameserver
        image: quay.io/burrsutter/balloon-game-server-jvm:1.0.5
        ports:
          - containerPort: 8080
        env:
        - name: MP_JWT_VERIFY_PUBLICKEY_LOCATION
          value: /usr/app/publicKey 
        - name: CONFIGSERVICE_MP_REST_URL
          value: http://configservice:8080
        - name: LOCATION_KEY
          value: GKE
        volumeMounts:
            - name: public-key
              mountPath: "/usr/app"
              readOnly: true
      volumes:
        - name: public-key
          secret:
            secretName: jwt-public-key
            items:
              - key: publicKey
                path: publicKey
        # resources:
        #   requests:
        #     memory: "300Mi"
        #     cpu: "250m" # 1/4 core
        #   limits:
        #     memory: "400Mi"
        #     cpu: "1000m" # 1 core
        # livenessProbe:
        #   httpGet:
        #       port: 8080
        #       path: /
        #   initialDelaySeconds: 1
        #   periodSeconds: 5
        #   timeoutSeconds: 2
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   initialDelaySeconds: 1
        #   periodSeconds: 3
