apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice
  namespace: game
  labels:
    app: configservice
  annotations:
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
      annotations:
        visualize: "true"
    spec:
      containers:
      - name: configservice
        image: gcr.io/devnexus-balloons/configuration-service-q
        ports:
          - containerPort: 8080
        env:
        - name: QUARKUS_HTTP_PORT
          value: '8080'
