apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: istio-backend-config
  namespace: istio-system
spec:
  cdn:
    enabled: false
  timeoutSec: 600
  sessionAffinity:
    affinityType: CLIENT_IP
